version: '2.23'

services:
  townhall:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    # TODO: change this to be file specific and reorganize the dockerfile
    volumes:
      - .:/app
    command: tail -f /dev/null
