name: Test

on: [pull_request]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.1
      with:
        submodules: true

    - name: Pull & Update Submodules Recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: 3.10.13
        cache: 'pip'

    - name: System Packages
      run: sudo apt update && sudo apt install -y portaudio19-dev

    - name: Install Dependencies
      run: pip install -r requirements.txt && pip install -e ext/tinygrad

    - name: Run Tests
      run: pytest