name: Test

on: [push, pull_request]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      with:
        submodules: true

    - name: Pull & update submodules recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: 3.10.13

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest